name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      
    - name: Login to docekr hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: build a new image
      run: docker compose build app

    - name: push it into docker hub
      run: docker compose push app
    
    - name: make deploy.sh executable
      run: chmod +x deploy.sh

    - name: integrate Deployement
      run: ./deploy.sh
      
    
